// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxNgHFiZ77hX_RFfW4rtyW2QbLuUT4hVE',
    appId: '1:805894420742:web:78798d14ca9abf449c8687',
    messagingSenderId: '805894420742',
    projectId: 'my-appp-52d39',
    authDomain: 'my-appp-52d39.firebaseapp.com',
    storageBucket: 'my-appp-52d39.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxU-z8lS3Y4goIRBo7IMcdRDfK9NM23wE',
    appId: '1:805894420742:android:bcf2fb2946e4af469c8687',
    messagingSenderId: '805894420742',
    projectId: 'my-appp-52d39',
    storageBucket: 'my-appp-52d39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVl53IhOaBaXOCV9cG5t93Y0yR_L9Pa8Q',
    appId: '1:805894420742:ios:cbea770020f29b2b9c8687',
    messagingSenderId: '805894420742',
    projectId: 'my-appp-52d39',
    storageBucket: 'my-appp-52d39.firebasestorage.app',
    iosBundleId: 'com.example.myAppp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVl53IhOaBaXOCV9cG5t93Y0yR_L9Pa8Q',
    appId: '1:805894420742:ios:cbea770020f29b2b9c8687',
    messagingSenderId: '805894420742',
    projectId: 'my-appp-52d39',
    storageBucket: 'my-appp-52d39.firebasestorage.app',
    iosBundleId: 'com.example.myAppp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxNgHFiZ77hX_RFfW4rtyW2QbLuUT4hVE',
    appId: '1:805894420742:web:3cae92c8f15ade6d9c8687',
    messagingSenderId: '805894420742',
    projectId: 'my-appp-52d39',
    authDomain: 'my-appp-52d39.firebaseapp.com',
    storageBucket: 'my-appp-52d39.firebasestorage.app',
  );
}
